CREATE DATABASE QuitQEcom
use QuitQEcom

CREATE TABLE Users(
Id INT PRIMARY KEY IDENTITY,
FirstName VARCHAR(MAX),
LastName VARCHAR(MAX),
UserName VARCHAR(MAX),
ContactNumber VARCHAR(MAX),
Password VARCHAR(MAX),
Email VARCHAR(MAX),
Role VARCHAR(MAX) -- CUSTOMER,SELLER,ADMIN
)


CREATE TABLE Product(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(MAX),
Description VARCHAR(MAX),
Price DECIMAL,
Stock INT,
ImageUrl VARCHAR(MAX),
SellerId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
CategoryId INT FOREIGN KEY REFERENCES ProductCategory(Id) ON DELETE CASCADE,
SubCategoryId INT FOREIGN KEY REFERENCES SubCategory(Id) 
)

CREATE TABLE ProductCategory(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(MAX)
)

CREATE TABLE SubCategory(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(MAX),
CategoryId INT FOREIGN KEY REFERENCES ProductCategory(Id) ON DELETE CASCADE
)

CREATE TABLE Cart(
Id INT PRIMARY KEY IDENTITY,
UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE
)

CREATE TABLE CartItem(
    Id INT PRIMARY KEY IDENTITY,
    CartId INT FOREIGN KEY REFERENCES Cart(Id) ON DELETE NO ACTION,
    ProductId INT FOREIGN KEY REFERENCES Product(Id) ON DELETE NO ACTION,
    Quantity INT
);

CREATE TRIGGER trg_DeleteCartItem
ON Cart
FOR DELETE
AS
BEGIN
    DELETE FROM CartItem
    WHERE CartId IN (SELECT Id FROM DELETED);
END;

CREATE TRIGGER trg_DeleteCartItemOnProduct
ON Product
FOR DELETE
AS
BEGIN
    DELETE FROM CartItem
    WHERE ProductId IN (SELECT Id FROM DELETED);
END;

CREATE TABLE Orders (
    Id INT PRIMARY KEY IDENTITY,
    UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE NO ACTION,
    ProductId INT FOREIGN KEY REFERENCES Product(Id) ON DELETE NO ACTION,
    OrderDate DATETIME,
    Quantity INT,
    OrderStatus VARCHAR(MAX)
);

CREATE TRIGGER trg_DeleteOrdersOnUser
ON Users
FOR DELETE
AS
BEGIN
    DELETE FROM Orders
    WHERE UserId IN (SELECT Id FROM DELETED);
END;

CREATE TRIGGER trg_DeleteOrdersOnProduct
ON Product
FOR DELETE
AS
BEGIN
    DELETE FROM Orders
    WHERE ProductId IN (SELECT Id FROM DELETED);
END;


CREATE TABLE DeliveryAddress(
Id INT PRIMARY KEY IDENTITY,
UserId INT FOREIGN KEY REFERENCES USERS(Id) ON DELETE CASCADE,
Address VARCHAR(MAX),
City VARCHAR(MAX),
Pincode VARCHAR(MAX),
Phone VARCHAR(MAX),
Notes TEXT
)

CREATE TABLE Payment(
Id INT PRIMARY KEY IDENTITY,
OrderId INT FOREIGN KEY REFERENCES Orders(Id) ON DELETE CASCADE,
Status VARCHAR(MAX),
Method VARCHAR(MAX),
PaymentDate DATETIME
)

CREATE TABLE Reviews (
    Id INT PRIMARY KEY IDENTITY,
    UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE NO ACTION,
    ProductId INT FOREIGN KEY REFERENCES Product(Id) ON DELETE NO ACTION,
    Rating DECIMAL,
    Comment VARCHAR(MAX),
    ReviewDate DATETIME
);

CREATE TRIGGER trg_DeleteReviewsOnUser
ON Users
FOR DELETE
AS
BEGIN
    DELETE FROM Reviews
    WHERE UserId IN (SELECT Id FROM DELETED);
END;

CREATE TRIGGER trg_DeleteReviewsOnProduct
ON Product
FOR DELETE
AS
BEGIN
    DELETE FROM Reviews
    WHERE ProductId IN (SELECT Id FROM DELETED);
END;


